More unwrap(), best practice; use try!()
This commit is re implementing the fn `merge_options_and_config()` to
use `try!()` instead of just unwrapping the Results.

This is not yet fixing the problem but now the CLI won't explode,
instead it will display a proper output:
```
Chef Delivery
Cannot find a .git/config file. Run 'git init' in your project root to initialize it.
```

Instead of:
```
Chef Delivery
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeliveryError { kind: NoGitConfig, detail: None }', ../src/libcore/result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Signed-off-by: Salim Afiune <afiune@chef.io>